networks:
  etcd_etcd:
    external: true
  
services:
  etcdctl:
    image: quay.io/coreos/etcd:v3.5.6
    entrypoint: ["/bin/sh"]
    environment:
      ETCDCTL_ENDPOINTS: http://etcd:2379
    networks:
    - etcd_etcd