version: "3.9"

networks:
  traefik:
    external: true

services:
  proxy:
    image: mitmproxy/mitmproxy:latest
    command: mitmweb --web-host 0.0.0.0 --no-web-open-browser
    networks:
    - traefik
    tty: true
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.mitmproxy_mitmweb.rule: Host(`mitm.${DOMAIN}`)
        traefik.http.services.mitmproxy_mitmweb.loadbalancer.server.port: 8081
        traefik.http.services.mitmproxy_mitmweb.loadbalancer.passhostheader: "false"
#        traefik.http.middlewares.mitmproxy_localhost.headers.customrequestheaders.Host: ""
        traefik.http.middlewares.mitmproxy_localhost.headers.customrequestheaders.Origin: ""
        traefik.http.routers.mitmproxy_mitmweb.middlewares: mitmproxy_localhost
      placement:
        constraints:
          - node.role==worker
