version: "3.9"

configs:
  rabbitmq-1:
    file: rabbitmq.conf

networks:
  traefik:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq{{.Task.Slot}}
    environment:
      RABBITMQ_ERLANG_COOKIE: "{{ .Service.ID }}"
    configs:
    - source: rabbitmq-1
      target: /etc/rabbitmq/rabbitmq.conf
    networks:
    - traefik
    - default
    volumes:
    - /var/lib/rabbitmq
    deploy:
      replicas: 3
      labels:
        traefik.enable: "true"
        traefik.http.routers.demo_rabbitmq.rule: HostRegexp("rabbitmq{any:.*}")
        traefik.http.services.rabbitmq.loadbalancer.server.port: 15672
