version: "3.9"

volumes:
  transit:
    driver: shared
  vault:
    driver: shared
    name: demo_vault_{{.Task.Slot}}

services:
  transit:
    image: hashicorp/vault:latest
    command: server
    volumes:
    - transit:/vault/file
    environment:
      SKIP_SETCAP: 1
      VAULT_ADDR: http://localhost:8200
     
      VAULT_LOCAL_CONFIG: >
        {
          "storage": {
            "file": {
              "path": "/vault/file"
            }
          },  
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": true
              }
            }
          ],
          "disable_mlock": true,
          "api_addr": "http://transit:8200"
        }
    healthcheck:
      test: |
        vault status
        if [ $$? -eq 2 ]; then
          vault operator unseal $UNSEAL_KEY
        fi
  vault:
    image: hashicorp/vault:latest
    command: server
    hostname: vault{{.Task.Slot}}
    environment:
      SKIP_SETCAP: 1
      VAULT_ADDR: http://localhost:8200
      VAULT_LOCAL_CONFIG: >
        {
          "storage": {
            "raft": {
              "path": "/vault/file",
              "node_id": "vault_{{.Task.Slot}}",
              "retry_join": [
                {
                  "leader_api_addr": "http://vault{{if eq .Task.Slot "1"}}2{{else if eq .Task.Slot "2"}}1{{else if eq .Task.Slot "3"}}1{{end}}:8200"
                },
                {
                  "leader_api_addr": "http://vault{{if eq .Task.Slot "1"}}3{{else if eq .Task.Slot "2"}}3{{else if eq .Task.Slot "3"}}2{{end}}:8200"
                }
              ]
            }
          },
          "seal": {
            "transit" : {
              "address": "http://transit:8200",
              "token": "${VAULT_TOKEN}",
              "disable_renewal": "false",
              "key_name": "unseal_key",
              "mount_path": "transit/"
            }
          },
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": true
              }
            }
          ],
          "disable_mlock": true,
          "default_lease_ttl": "168h",
          "max_lease_ttl": "720h",
          "ui": true,
          "api_addr": "http://vault{{.Task.Slot}}:8200",
          "cluster_addr": "http://vault{{.Task.Slot}}:8201"
        }
    volumes:
    - vault:/vault/file
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.role==worker

  agent:
    image: hashicorp/vault:latest
    command: agent -config=/vault/config
    environment:
      SKIP_SETCAP: 1
      VAULT_ADDR: http://vault:8200
      VAULT_LOCAL_CONFIG: >
        {
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": true
              }
            }
          ]
        }
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.role==worker
