server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:

- job_name: containers
  static_configs:
  - targets:
      - localhost
    labels:
      job: containerlogs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:
  - json:
      expressions:
        log: log
        stream: stream
        time: time
        tag: attrs.tag
        swarm_stack: attrs."com.docker.stack.namespace"
        container_name: attrs."com.docker.swarm.task.name"
        swarm_service: attrs."com.docker.swarm.service.name"
        compose_project: attrs."com.docker.compose.project"
        compose_service: attrs."com.docker.compose.service"
  - regex:
      expression: "^/var/lib/docker/containers/(?P<container_id>.{12}).+/.+-json.log$"
      source: filename
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      stream:
      container_id:
      swarm_stack:
      swarm_service:
      container_name:
      compose_project:
      compose_service:
      tag:
  - output:
      source: log